# Generated by Django 4.2.4 on 2023-11-12 01:27

import aplicacionAdministrador.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='administradores',
            fields=[
                ('rutAdministrador', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[aplicacionAdministrador.models.validar_rut])),
                ('nombreAdm', models.CharField(max_length=30)),
                ('apellidosAdm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cuarteles',
            fields=[
                ('idCuartel', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cuartel', models.CharField(max_length=30)),
                ('direccionCuartel', models.TextField(default='')),
                ('voluntarios_in', models.IntegerField(default=0)),
                ('unidades_in', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='unidades',
            fields=[
                ('nomenclatura', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=8)),
                ('estado_unidad', models.BooleanField(default=True)),
                ('especialidad', models.CharField(max_length=15)),
                ('comentario', models.TextField()),
                ('cuartel_actual_uni', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='aplicacionAdministrador.cuarteles')),
            ],
        ),
        migrations.CreateModel(
            name='voluntarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[aplicacionAdministrador.models.validar_rut])),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=15)),
                ('telefono', models.PositiveBigIntegerField(blank=True)),
                ('compania', models.CharField(max_length=10)),
                ('numero_registro', models.IntegerField(unique=True)),
                ('estado', models.BooleanField(default=False)),
                ('direccion', models.TextField(blank=True)),
                ('unidad_asignada', models.CharField(default=0, max_length=4)),
                ('cuartel_actual_vol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='aplicacionAdministrador.cuarteles')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', aplicacionAdministrador.models.VoluntarioManager()),
            ],
        ),
    ]
