# Generated by Django 4.2.4 on 2023-11-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0002_alter_voluntarios_apellidos_alter_voluntarios_cargo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administradores',
        ),
    ]
