# Generated by Django 4.2.7 on 2023-11-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0003_delete_administradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntarios',
            name='conductor',
            field=models.BooleanField(default=False),
        ),
    ]
