# Generated by Django 4.2.7 on 2023-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0004_voluntarios_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntarios',
            name='unidad_asignada',
        ),
        migrations.AddField(
            model_name='cuarteles',
            name='conductores_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='nomenclatura',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
