# Generated by Django 4.2.7 on 2023-11-21 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0005_remove_voluntarios_unidad_asignada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergencias',
            fields=[
                ('id_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(default=0, max_length=15)),
                ('direccion_emergencia', models.TextField()),
                ('fecha_emergencia', models.DateField(auto_now_add=True)),
                ('emergencias_unidades', models.ManyToManyField(to='aplicacionAdministrador.unidades')),
                ('emergencias_voluntarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
