# Generated by Django 4.2.7 on 2023-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0007_remove_emergencias_emergencias_unidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencias',
            name='comentarioEmergencia',
            field=models.TextField(default=''),
        ),
    ]
