# Generated by Django 4.2.7 on 2023-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0008_emergencias_comentarioemergencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencias',
            name='EmergenciaActiva',
            field=models.BooleanField(default=True),
        ),
    ]
