# Generated by Django 4.2.7 on 2023-11-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0009_emergencias_emergenciaactiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencias',
            name='fecha_emergencia',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
