# Generated by Django 4.2.7 on 2023-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0010_alter_emergencias_fecha_emergencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencias',
            name='EmergenciaDepachada',
            field=models.BooleanField(default=False),
        ),
    ]
