# Generated by Django 4.2.7 on 2023-12-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAdministrador', '0011_emergencias_emergenciadepachada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntarios',
            name='numero_registro',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='telefono',
            field=models.PositiveBigIntegerField(blank=True, default=9),
        ),
    ]
